import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";

import { ClerkProvider } from "@clerk/nextjs";
import { currentUser } from "@clerk/nextjs/server";
import GraphicEqIcon from "@mui/icons-material/GraphicEq";
import { AppBar, Box, Button, Toolbar } from "@mui/material";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import AuthButtons from "@/components/AuthButtons";
import { prisma } from "@/lib/prisma";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // TODO: remove testing console.log
  const user = await currentUser();
  console.log("current user >>>>", user);

  const users = await prisma.user.findMany();
  console.log("users >>>>", users);

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <AppBar position="fixed" component="nav">
            <Toolbar variant="dense">
              <GraphicEqIcon />
              <Box flexGrow="1">
                <Button color="inherit">Hymns</Button>
              </Box>
              <Box flexGrow="0">
                <AuthButtons />
              </Box>
            </Toolbar>
          </AppBar>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
