import "@fontsource/roboto/300.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/700.css";
// import LabelIcon from "@mui/icons-material/Label";
// import PersonIcon from "@mui/icons-material/Person";
import Image from "next/image";
import GraphicEqIcon from "@mui/icons-material/GraphicEq";
import { AppBar, Box, Button, Toolbar } from "@mui/material";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppBar position="fixed" component="nav">
          <Toolbar variant="dense">
            <GraphicEqIcon />
            <Box flexGrow="1">
              <Button color="inherit">Hymns</Button>
            </Box>
            <Box flexGrow="0">
              <Button
                color="inherit"
                startIcon={
                  <Image
                    src="/google-icon.svg"
                    alt="Google logo"
                    width={20}
                    height={20}
                  />
                }
              >
                Sign in with Google
              </Button>
            </Box>
          </Toolbar>
        </AppBar>
        {children}
      </body>
    </html>
  );
}
